const ListaProductos= [
{
 nombre:"Maiz 2024",
CantidadDisponible: 40,
precio: 10000, 
imagen:"https://static.vecteezy.com/system/resources/previews/021/964/645/non_2x/corn-fruit-cartoon-colored-clipart-illustration-free-vector.jpg",
codigo:"p001",
},
{
nombre: "Trigo 2024",
CantidadDisponible: 40,
precio: 11000, 
imagen:"",
codigo:"p002",
},
{
nombre: "Arroz 2024",
CantidadDisponible: 40,
precio: 12000, 
imagen:"",
codigo:"p003",
},
{
nombre:"Cebada 2024",
CantidadDisponible: 40,
precio: 13000, 
imagen:"",
codigo:"p004",
},
{
nombre:"Sorgo 2024",
CantidadDisponible: 40,
precio: 14000, 
imagen:"",
codigo:"p005",
},
{
nombre:"Avena 2024",
CantidadDisponible: 40,
precio: 15000, 
imagen:"",
codigo:"p006",
},
{
nombre:"Soja 2024",
CantidadDisponible: 40,
precio: 16000, 
imagen:"",
codigo:"p007",
},
{
nombre:"Girasol 2024",
CantidadDisponible: 40,
precio: 17000, 
imagen:"",
codigo:"p008",
},
{
nombre:"Caña de Azucar2024",
CantidadDisponible: 40,
precio: 18000, 
imagen:"",
codigo:"p009",
},
{
nombre:"Papa 2024",
CantidadDisponible: 40,
precio: 19000, 
imagen:"",
codigo:"p010",
},
{
nombre:"Batata 2024",
CantidadDisponible: 40,
precio: 20000, 
imagen:"",
codigo:"p011",
},
{
nombre:"Zanahoria 2024",
CantidadDisponible: 40,
precio: 21000, 
imagen:"",
codigo:"p012",
},
{
nombre:"Cebolla 2024",
CantidadDisponible: 40,
precio: 22000, 
imagen:"",
coodigo:"p013",
},
{
nombre:"Tomate 2024",
CantidadDisponible: 40,
precio: 23000, 
imagen:"",
codigo:"p014",
},
{
nombre:"Pimiento2024",
CantidadDisponible: 40,
precio: 24000, 
imagen:"",
codigo:"p015",
},
{
nombre:"Lechuga 2024",
CantidadDisponible: 40,
precio: 25000, 
imagen:"",
codigo:"p016",
},
{
nombre:"Espinaca2024",
CantidadDisponible: 40,
precio: 26000, 
imagen:"",
codigo: "p017",
},
{
nombre : "Brocoli 2024",
cantidadDisponible : 40,
precio: 27000,
imagen :"",
codigo:"p018",
},
{
    nombre:"Coliflor 2024",
    CantidadDisponible: 40,
    precio: 28000, 
    imagen:"",
    codigo:"p019",
    },
    {
    nombre:"Pepino 2024",
    CantidadDisponible: 40,
    precio: 29000, 
    imagen:"",
    codigo:"p020",
    },
    {
    nombre:"Clabacin 2024",
    CantidadDisponible: 40,
    precio: 30000, 
    imagen:"",
    codigo:"p021",
    },
    {
    nombre:"Berenjena 2024",
    CantidadDisponible: 40,
    precio: 31000, 
    imagen:"",
    codigo: "p022",
    },
    {
    nombre : "Frijoles 2024",
    cantidadDisponible : 40,
    precio: 32000,
    imagen :"",
    codigo:"p023",
    },
    {
        nombre:"Coliflor 2024",
        CantidadDisponible: 40,
        precio: 28000, 
        imagen:"",
        codigo:"p019",
        },
        {
        nombre:"Pepino 2024",
        CantidadDisponible: 40,
        precio: 29000, 
        imagen:"",
        codigo:"p020",
        },
        {
        nombre:"Clabacin 2024",
        CantidadDisponible: 40,
        precio: 30000, 
        imagen:"",
        codigo:"p021",
        },
        {
        nombre:"Berenjena 2024",
        CantidadDisponible: 40,
        precio: 31000, 
        imagen:"",
        codigo: "p022",
        },
        {
        nombre : "Frijoles 2024",
        cantidadDisponible : 40,
        precio: 32000,
        imagen :"",
        codigo:"p023",
        },
        {
            nombre:"Lentejas 2024",
            CantidadDisponible: 40,
            precio: 33000, 
            imagen:"",
            codigo:"p024",
            },
            {
            nombre:"Garbanzos 2024",
            CantidadDisponible: 40,
            precio: 34000, 
            imagen:"",
            codigo:"p025",
            },
            {
            nombre:"Almendra 2024",
            CantidadDisponible: 40,
            precio: 35000, 
            imagen:"",
            codigo:"p026",
            },
            {
            nombre:"Nueces 2024",
            CantidadDisponible: 40,
            precio: 36000, 
            imagen:"",
            codigo: "p027",
            },
            {
            nombre : "Cacahuate 2024",
            cantidadDisponible : 40,
            precio: 37000,
            imagen :"",
            codigo:"p028",
            },
            {
                nombre:"Platano 2024",
                CantidadDisponible: 40,
                precio: 38000, 
                imagen:"",
                codigo:"p029",
                },
                {
                nombre:"Manzana 2024",
                CantidadDisponible: 40,
                precio: 39000, 
                imagen:"",
                codigo:"p030",
                },
                {
                nombre:"Naranja 2024",
                CantidadDisponible: 40,
                precio: 40000, 
                imagen:"",
                codigo:"p031",
                },
                {
                nombre:"Limon 2024",
                CantidadDisponible: 40,
                precio: 41000, 
                imagen:"",
                codigo: "p032",
                },
                {
                nombre : "Fresa 2024",
                cantidadDisponible : 40,
                precio: 42000,
                imagen :"",
                codigo:"p033",
                },
                {
                    nombre:"Uva 2024",
                    CantidadDisponible: 40,
                    precio: 43000, 
                    imagen:"",
                    codigo: "p034",
                    },
                    {
                    nombre : "Piña 2024",
                    cantidadDisponible : 40,
                    precio: 44000,
                    imagen :"",
                    codigo:"p035",
                    },
                    {
                        nombre:"Mango 2024",
                        CantidadDisponible: 40,
                        precio: 45000, 
                        imagen:"",
                        codigo:"p036",
                        },
                        {
                        nombre:"Papaya 2024",
                        CantidadDisponible: 40,
                        precio: 46000, 
                        imagen:"",
                        codigo:"p037",
                        },
                        {
                        nombre:"Aguacate  2024",
                        CantidadDisponible: 40,
                        precio: 47000, 
                        imagen:"",
                        codigo:"p038",
                        },
                        {
                        nombre:"Coco 2024",
                        CantidadDisponible: 40,
                        precio: 48000, 
                        imagen:"",
                        codigo: "p039",
                        },
                        {
                        nombre : "Oliva 2024",
                        cantidadDisponible : 40,
                        precio: 49000,
                        imagen :"",
                        codigo:"p040",
                        }
]